name: Enable auto-merge for Snyk PRs

on:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate token from GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ENABLE_AUTO_MERGE_PR_BOT_APP_ID }}
          private-key: ${{ secrets.ENABLE_AUTO_MERGE_PR_BOT_PRIVATE_KEY }}

      - name: Enable auto-merge for Snyk PR
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}